### ISSUE TITLE
Why not register with stackage?

### ISSUE THREAD

**Issue by igrep** [nushio3/unicode-show#1]
I'd be happy if unicode-show were in stackage because I could use it without adding to `extra-deps` in my stack.yaml.
It's annoying to add it to `extra-deps` in almost any projects just for debugging.
I guess unicode-show can be registered without any trouble because it depends on almost nothing.

To register with stackage, follow this instruction (copied from https://www.stackage.org/):

> - [Edit the build-constraints.yaml](https://github.com/fpco/stackage/edit/master/build-constraints.yaml) file to add your packages, following the same format as other contributors
> - Choose "Create a new branch for this commit"
> - Click "Propose file change"
> - If there are any issues building your packages, one of the Stackage maintainers will contact you with more information.

[This pull request, when I reigster my package,](https://github.com/fpco/stackage/pull/1069) may help you.

Thanks for very nice package :star2:

**Comment by nushio3** [comment]
Good idea! and thank you for using this package.

**Comment by nushio3** [comment]
Submitted. https://github.com/fpco/stackage/pull/1526

**Comment by nushio3** [comment]
Merged!
